name: Build and Deploy Webpack to GitHub Pages

on:
  push:
    branches: 
    - main

jobs:
  # Build job
  build:
    # Specify runner + build step
    runs-on: ubuntu-latest
    steps: 
      # Setup the project in a NodeJS environment
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    # Run the project build command which outputs to 'dist'
    - name: Install and Build 🔧
      run: | 
        npm ci
        npm run build

    # Upload the 'dist' directory to be used in the deploy job
    - name: Upload pages artifact 📦
      uses: actions/upload-pages-artifact@v1.0.4
      with:
        path: build/

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1